---
version: "2.1"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=
      - WEBUI_PORT=8090 
    volumes:
      - /dockdata/qbittorent/appdata/config:/config
      - :/downloads
    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped


#indexers

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true #optional
    volumes:
      - /dockdata/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /dockdata/bazarr:/config
      - /data/movies:/movies #optional
      - /data/tvseries:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /dockdata/sonarr:/config
      - /data/tvseries:/tv #optional
      - /dockdata/qbittorent/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped